src/WebPushApi/Models/ErrorViewModel.cs
namespace WebPushApi.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

src/WebPushApi/Models/PushRegisterViewModel.cs
namespace WebPushApi.Models
{
    public class PushRegisterViewModel
    {

        public string? PublicKey { get; set; }
    }
}

src/WebPushApi/Models/SubscribeViewModel.cs
namespace WebPushApi.Models
{
    public class SubscribeViewModel
    {

        public string? Endpoint { get; set; }

        public string? ExpirationTime {  get; set; }

        public SubscribeKey? Keys { get; set; }

        public class SubscribeKey
        {
            public string? P256dh {  get; set;}

            public string? Auth { get; set; }
        }
    }
}

src/WebPushApi/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using WebPushApi.Models;

namespace WebPushApi.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

src/WebPushApi/Controllers/PushController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using WebPushApi.Models;

namespace WebPushApi.Controllers;

public class PushController : Controller
{
    private readonly ILogger<PushController> _logger;

    private readonly Options.VapidOption _vapidOption;

    public PushController(ILogger<PushController> logger, Options.VapidOption vapidOptions)
    {
        _logger = logger;
        _vapidOption = vapidOptions;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Register()
    {
        var vm = new Models.PushRegisterViewModel();
        vm.PublicKey = _vapidOption.PublicKey;
        return View(vm);
    }

    public IActionResult SendPush()
    {
        return View();
    }

    public static Models.SubscribeViewModel _subscribeViewModel;

    [HttpPost]
    public void Subscribe([FromBody]Models.SubscribeViewModel subscribeViewModel)
    {
        _subscribeViewModel = subscribeViewModel;
    }

    public async Task Trigger()
    {

        var client = new WebPush.WebPushClient();
        var subscription = new WebPush.PushSubscription
        {
            Auth = _subscribeViewModel.Keys.Auth,
            P256DH = _subscribeViewModel.Keys.P256dh,
            Endpoint = _subscribeViewModel.Endpoint
        };
        var vapid = new WebPush.VapidDetails();
        vapid.Subject = "mailto:test@example.com";
        vapid.PublicKey = _vapidOption.PublicKey;
        vapid.PrivateKey = _vapidOption.PrivateKey;
        var payload = System.Text.Json.JsonSerializer.Serialize(new { title = "title", msg = "message", icon = "/images/icon.jpg" });
        try
        {
            await client.SendNotificationAsync(subscription, payload, vapid);
        }catch (Exception ex)
        {
            Debug.WriteLine(ex);
        }
    }

}

src/WebPushApi/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

src/WebPushApi/Views/Home/Register.cshtml
<p>
    <button id="register-service-worker">ServiceWorkerの登録</button>
</p>

@section Scripts {
<script>
  windows.onload = () => {
    var btnRegister = document.querySelector("button#register-service-worker");
    btnRegister.addEventListener("click", ev => {
      ev.preventDefault();
      window.navigator.serviceWorker.register("service-worker.js").then(registration => {
        logger.line("Register OK:", registration);
        _registration = registration;
      }).catch(err => {
        logger.line("Register Error:", err);
      });
    });
  }
</script>
}

src/WebPushApi/Views/Push/Index.cshtml
<ol>
    <li><a asp-area="" asp-controller="Push" asp-action="Register">Register&Subscribe</a></li>
    <li><a asp-area="" asp-controller="Push" asp-action="SendPush">SendPush</a></li>
</ol>

src/WebPushApi/Views/Push/Register.cshtml
@model PushRegisterViewModel

<p>
    <button id="register-service-worker">ServiceWorkerの登録</button>
</p>

<p>
    <button id="start-subscribe">Subscribeの登録</button>
</p>

<p>
    <button id="stop-service-worker">ServiceWorkerの削除</button>
</p>

<p>Subscribeの登録が失敗する場合はブラウザの開発ツールよりサイトデータの削除を行う</p>


@section Scripts {
<script>
    const urlB64ToUint8Array = (base64String) => {
        const padding = "=".repeat((4 - base64String.length % 4) % 4);
        const base64 = (base64String + padding).replace(/\-/g, "+").replace(/_/g, "/");
        const rawData = window.atob(base64);
        const outputArray = new Uint8Array(rawData.length);
        for (let i = 0; i < rawData.length; ++i) {
            outputArray[i] = rawData.charCodeAt(i);
        }
        return outputArray;
    }

    var _registration = null;

    const btnRegister = document.querySelector("button#register-service-worker");
    btnRegister.addEventListener("click", ev => {
      ev.preventDefault();
      window.navigator.serviceWorker.register("/js/service-worker.js").then(registration => {
        console.log("Register OK:", registration);
        btnRegister.innerHTML += " 済み";
        _registration = registration;
      }).catch(err => {
        console.log("Register Error:", err);
      });
    });

    const btnSubscribe = document.querySelector("button#start-subscribe");
    btnSubscribe.addEventListener("click", ev => {
        ev.preventDefault();
        _registration.pushManager.subscribe({
            userVisibleOnly: true,
            applicationServerKey: urlB64ToUint8Array("@Model.PublicKey"),
        }).then(subscription => {
            console.log("Subscribe OK:", subscription);
            btnSubscribe.innerHTML += " 済み";
            return fetch("/push/subscribe", {
                method: "POST",
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(subscription),
            });
        }).then(() => {
            console.log("Server Stored Subscription.");
        }).catch(err => {
            console.log("Subscribe Error:", err);
            console.error("[main.js][Subscription]", err);
        });
    });

    const btnUnregister = document.querySelector("button#stop-service-worker");
    btnUnregister.addEventListener("click", ev => {
        ev.preventDefault();
        if ('serviceWorker' in navigator) {
            navigator.serviceWorker.getRegistrations().then(function (registrations) {
                //returns installed service workers
                if (registrations.length) {
                    for (let registration of registrations) {
                        registration.unregister();
                    }
                }
            });
        }
        btnUnregister.innerHTML += " 済み";
    });

</script>
}

src/WebPushApi/Views/Push/SendPush.cshtml
<p>
    <button id="send-push">SendPush</button>
</p>

@section Scripts {
<script>
    const btnSendPush = document.querySelector("button#send-push");
    btnSendPush.addEventListener("click", ev => {
        ev.preventDefault();
        fetch("/push/trigger");
        console.log("Just triggered server to publish notifications.");
    });
</script>
}

src/WebPushApi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebPushApi</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebPushApi.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebPushApi</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Push" asp-action="Index">Push</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WebPushApi - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>